import type { ItemCatalogo } from './tipos';

/**
 * Catálogo curado de itens do enxoval.
 *
 * RASCUNHO — todo o conteúdo está pendente de revisão por profissional de saúde
 * (pediatra/enfermeira) antes da publicação na loja. Itens "evitar" só entram com fonte oficial.
 */

const SONO_SEGURO = 'Sociedade Brasileira de Pediatria (SBP) — recomendações de sono seguro';
const ALEITAMENTO = 'Ministério da Saúde — orientações sobre aleitamento materno';

export const CATALOGO: ItemCatalogo[] = [
  // Quarto e sono
  {
    id: 'berco',
    nome: 'Berço',
    categoria: 'quarto',
    prioridade: 'essencial',
    quando: 'tri2',
    quantidade: 1,
    porque:
      'Lugar seguro para o bebê dormir. Confira o selo do Inmetro e o espaço entre as grades.',
    fonte: SONO_SEGURO,
    inmetro: true,
    busca: 'berço infantil',
  },
  {
    id: 'colchao-berco',
    nome: 'Colchão de berço',
    categoria: 'quarto',
    prioridade: 'essencial',
    quando: 'tri2',
    quantidade: 1,
    porque: 'Deve ser firme e do tamanho exato do berço, sem vãos nas laterais.',
    fonte: SONO_SEGURO,
    busca: 'colchão de berço',
  },
  {
    id: 'lencol-elastico',
    nome: 'Lençol com elástico',
    categoria: 'quarto',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 4,
    porque: 'O elástico mantém o lençol bem preso ao colchão. Tenha reservas para as trocas.',
    busca: 'lençol de berço com elástico',
  },
  {
    id: 'capa-colchao',
    nome: 'Capa impermeável para colchão',
    categoria: 'quarto',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 2,
    porque: 'Protege o colchão de vazamentos de fralda e facilita a limpeza.',
    busca: 'capa impermeável colchão berço',
  },
  {
    id: 'saco-dormir',
    nome: 'Saco de dormir para bebê',
    categoria: 'quarto',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 2,
    porque: 'Aquece sem cobertor solto no berço.',
    fonte: SONO_SEGURO,
    busca: 'saco de dormir bebê',
  },
  {
    id: 'comoda-trocador',
    nome: 'Cômoda com trocador',
    categoria: 'quarto',
    prioridade: 'util',
    quando: 'tri2',
    quantidade: 1,
    porque: 'Facilita as trocas e guarda roupas. Uma bancada firme com trocador também resolve.',
    busca: 'cômoda com trocador',
  },
  {
    id: 'mosquiteiro',
    nome: 'Mosquiteiro',
    categoria: 'quarto',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Protege contra mosquitos sem uso de repelente no recém-nascido.',
    busca: 'mosquiteiro berço',
  },
  {
    id: 'luz-noturna',
    nome: 'Luz noturna',
    categoria: 'quarto',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Luz fraca para mamadas e trocas de madrugada sem acordar demais o bebê.',
    busca: 'luz noturna quarto bebê',
  },
  {
    id: 'baba-eletronica',
    nome: 'Babá eletrônica',
    categoria: 'quarto',
    prioridade: 'opcional',
    quando: 'depois',
    quantidade: 1,
    porque: 'Útil se o bebê dorme em outro cômodo. Dispensável em casas pequenas.',
    busca: 'babá eletrônica',
  },
  {
    id: 'berco-portatil',
    nome: 'Berço portátil ou moisés',
    categoria: 'quarto',
    prioridade: 'opcional',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Prático para viagens ou para o bebê ficar perto dos pais nos primeiros meses.',
    busca: 'berço portátil',
  },
  {
    id: 'protetor-berco',
    nome: 'Protetor de berço (kit berço)',
    categoria: 'quarto',
    prioridade: 'evitar',
    quando: 'tri2',
    quantidade: 0,
    porque: 'Aumenta o risco de sufocamento. O berço deve ficar livre de protetores e objetos.',
    fonte: SONO_SEGURO,
    busca: 'protetor de berço',
  },
  {
    id: 'travesseiro-bebe',
    nome: 'Travesseiro para bebê',
    categoria: 'quarto',
    prioridade: 'evitar',
    quando: 'tri2',
    quantidade: 0,
    porque: 'Não é recomendado no primeiro ano: risco de sufocamento.',
    fonte: SONO_SEGURO,
    busca: 'travesseiro bebê',
  },
  {
    id: 'pelucias-berco',
    nome: 'Pelúcias e almofadas no berço',
    categoria: 'quarto',
    prioridade: 'evitar',
    quando: 'tri2',
    quantidade: 0,
    porque: 'Objetos soltos no berço aumentam o risco de sufocamento durante o sono.',
    fonte: SONO_SEGURO,
    busca: 'almofada decorativa berço',
  },
  {
    id: 'edredom-berco',
    nome: 'Edredom ou cobertor solto no berço',
    categoria: 'quarto',
    prioridade: 'evitar',
    quando: 'tri2',
    quantidade: 0,
    porque: 'Pode cobrir o rosto do bebê. Prefira saco de dormir ou roupa adequada à temperatura.',
    fonte: SONO_SEGURO,
    busca: 'edredom berço',
  },

  // Passeio e transporte
  {
    id: 'bebe-conforto',
    nome: 'Bebê conforto',
    categoria: 'passeio',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 1,
    porque:
      'Obrigatório para transportar o bebê de carro. Necessário já na saída da maternidade, se for de carro.',
    fonte: 'Código de Trânsito Brasileiro e Resolução Contran nº 819/2021',
    inmetro: true,
    busca: 'bebê conforto',
  },
  {
    id: 'base-bebe-conforto',
    nome: 'Base para bebê conforto',
    categoria: 'passeio',
    prioridade: 'opcional',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Facilita encaixar o bebê conforto no carro. O cinto do carro também prende o assento.',
    busca: 'base bebê conforto',
  },
  {
    id: 'carrinho',
    nome: 'Carrinho de bebê',
    categoria: 'passeio',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 1,
    porque:
      'Para passeios mais longos. Modelos "travel system" encaixam o bebê conforto. Confira o selo do Inmetro.',
    inmetro: true,
    busca: 'carrinho de bebê',
  },
  {
    id: 'canguru',
    nome: 'Canguru ergonômico ou sling',
    categoria: 'passeio',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Deixa as mãos livres. Prefira modelos que mantêm as pernas do bebê em posição de "M".',
    busca: 'canguru ergonômico bebê',
  },
  {
    id: 'bolsa-maternidade',
    nome: 'Bolsa ou mochila de maternidade',
    categoria: 'passeio',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Leva fraldas, trocas de roupa e itens de higiene em toda saída.',
    busca: 'mochila maternidade',
  },
  {
    id: 'trocador-portatil',
    nome: 'Trocador portátil',
    categoria: 'passeio',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Superfície limpa para trocar fraldas fora de casa.',
    busca: 'trocador portátil bebê',
  },
  {
    id: 'andador',
    nome: 'Andador',
    categoria: 'passeio',
    prioridade: 'evitar',
    quando: 'depois',
    quantidade: 0,
    porque:
      'Associado a quedas e acidentes graves e não ajuda o bebê a andar. Não é recomendado pela SBP.',
    fonte: 'Sociedade Brasileira de Pediatria (SBP) — posicionamento sobre o uso de andadores',
    inmetro: true,
    busca: 'andador infantil',
  },

  // Higiene e banho
  {
    id: 'banheira',
    nome: 'Banheira',
    categoria: 'higiene',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Banho seguro nos primeiros meses. Nunca deixe o bebê sozinho no banho.',
    busca: 'banheira bebê',
  },
  {
    id: 'suporte-banheira',
    nome: 'Suporte para banheira',
    categoria: 'higiene',
    prioridade: 'opcional',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Deixa a banheira na altura certa e poupa a coluna de quem dá o banho.',
    busca: 'suporte banheira bebê',
  },
  {
    id: 'toalha-capuz',
    nome: 'Toalha com capuz',
    categoria: 'higiene',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 3,
    porque: 'Seca e aquece o bebê logo após o banho.',
    busca: 'toalha com capuz bebê',
  },
  {
    id: 'sabonete-neutro',
    nome: 'Sabonete líquido neutro para bebê',
    categoria: 'higiene',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Fórmulas suaves, sem perfume forte, para a pele sensível do recém-nascido.',
    busca: 'sabonete líquido bebê',
    precoPor: 'frasco',
  },
  {
    id: 'shampoo',
    nome: 'Shampoo infantil',
    categoria: 'higiene',
    prioridade: 'opcional',
    quando: 'depois',
    quantidade: 1,
    porque: 'No começo, o sabonete neutro costuma ser suficiente também para o cabelo.',
    busca: 'shampoo infantil',
    precoPor: 'frasco',
  },
  {
    id: 'algodao',
    nome: 'Algodão',
    categoria: 'higiene',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 2,
    porque: 'Para limpar o bebê nas trocas com água morna nas primeiras semanas.',
    busca: 'algodão bolas',
    precoPor: 'pacote',
  },
  {
    id: 'alcool-70',
    nome: 'Álcool 70% (coto umbilical)',
    categoria: 'higiene',
    prioridade: 'essencial',
    quando: 'maternidade',
    quantidade: 1,
    porque: 'Usado na higiene do coto umbilical. Siga a orientação da maternidade e do pediatra.',
    busca: 'álcool 70 líquido',
    precoPor: 'frasco',
  },
  {
    id: 'tesoura-unha',
    nome: 'Tesourinha ou lixa de unha para bebê',
    categoria: 'higiene',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Unhas compridas arranham o rosto do bebê. Pontas arredondadas são mais seguras.',
    busca: 'tesoura unha bebê',
  },
  {
    id: 'escova-cabelo',
    nome: 'Escova de cabelo macia',
    categoria: 'higiene',
    prioridade: 'opcional',
    quando: 'depois',
    quantidade: 1,
    porque: 'Cerdas macias. Muitos bebês nascem com pouco cabelo.',
    busca: 'escova cabelo bebê',
  },
  {
    id: 'lenco-umedecido',
    nome: 'Lenço umedecido',
    categoria: 'higiene',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 3,
    porque: 'Prático fora de casa. Em casa, algodão com água costuma irritar menos a pele.',
    busca: 'lenço umedecido bebê',
    precoPor: 'pacote',
  },
  {
    id: 'pomada-assadura',
    nome: 'Pomada para assaduras',
    categoria: 'higiene',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Cria uma barreira que protege a pele nas trocas de fralda.',
    busca: 'pomada assadura',
  },
  {
    id: 'fralda-rn',
    nome: 'Fralda descartável RN (pacote)',
    categoria: 'higiene',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 2,
    porque: 'Compre pouco no tamanho RN: o bebê cresce rápido e o P é o mais usado.',
    busca: 'fralda descartável RN',
    precoPor: 'pacote',
  },
  {
    id: 'fralda-p',
    nome: 'Fralda descartável P (pacote)',
    categoria: 'higiene',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 4,
    porque: 'Tamanho mais usado nos primeiros meses. Bom item para pedir no chá de bebê.',
    busca: 'fralda descartável P',
    precoPor: 'pacote',
  },
  {
    id: 'fralda-pano',
    nome: 'Fralda de pano',
    categoria: 'higiene',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 12,
    porque: 'Usada como babador, para arrotar, proteger o ombro e forrar o trocador.',
    busca: 'fralda de pano',
  },
  {
    id: 'lixeira-fralda',
    nome: 'Lixeira com tampa para fraldas',
    categoria: 'higiene',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Segura o cheiro das fraldas usadas perto do trocador.',
    busca: 'lixeira com tampa',
  },

  // Alimentação e amamentação
  {
    id: 'almofada-amamentacao',
    nome: 'Almofada de amamentação',
    categoria: 'alimentacao',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 1,
    porque: 'Ajuda a posicionar o bebê e reduz o cansaço nos braços e nas costas.',
    busca: 'almofada de amamentação',
  },
  {
    id: 'sutia-amamentacao',
    nome: 'Sutiã de amamentação',
    categoria: 'alimentacao',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 3,
    porque:
      'Abertura frontal facilita as mamadas. Compre perto do fim da gestação para acertar o tamanho.',
    busca: 'sutiã de amamentação',
  },
  {
    id: 'absorvente-seio',
    nome: 'Absorvente para seios',
    categoria: 'alimentacao',
    prioridade: 'util',
    quando: 'maternidade',
    quantidade: 1,
    porque: 'Evita manchas na roupa quando o leite vaza.',
    busca: 'absorvente para seios',
    precoPor: 'caixa',
  },
  {
    id: 'bomba-leite',
    nome: 'Bomba tira-leite',
    categoria: 'alimentacao',
    prioridade: 'opcional',
    quando: 'depois',
    quantidade: 1,
    porque: 'Útil para estocar leite, principalmente na volta ao trabalho. Dá para decidir depois.',
    busca: 'bomba tira leite',
  },
  {
    id: 'mamadeira',
    nome: 'Mamadeira',
    categoria: 'alimentacao',
    prioridade: 'opcional',
    quando: 'depois',
    quantidade: 1,
    porque:
      'Bicos artificiais podem atrapalhar a amamentação. Converse com o pediatra antes de usar.',
    fonte: ALEITAMENTO,
    inmetro: true,
    busca: 'mamadeira',
  },
  {
    id: 'chupeta',
    nome: 'Chupeta',
    categoria: 'alimentacao',
    prioridade: 'opcional',
    quando: 'depois',
    quantidade: 1,
    porque: 'Pode interferir na amamentação nas primeiras semanas. Converse com o pediatra.',
    fonte: ALEITAMENTO,
    inmetro: true,
    busca: 'chupeta',
  },
  {
    id: 'esterilizador',
    nome: 'Esterilizador',
    categoria: 'alimentacao',
    prioridade: 'opcional',
    quando: 'depois',
    quantidade: 1,
    porque: 'Só faz sentido se for usar mamadeira. Ferver em água também esteriliza.',
    busca: 'esterilizador de mamadeira',
  },
  {
    id: 'babador',
    nome: 'Babador',
    categoria: 'alimentacao',
    prioridade: 'util',
    quando: 'depois',
    quantidade: 4,
    porque: 'Protege a roupa durante golfadas e, mais tarde, na introdução alimentar.',
    busca: 'babador bebê',
  },
  {
    id: 'cadeira-alimentacao',
    nome: 'Cadeira de alimentação',
    categoria: 'alimentacao',
    prioridade: 'util',
    quando: 'depois',
    quantidade: 1,
    porque: 'Só é usada a partir da introdução alimentar, por volta dos 6 meses.',
    inmetro: true,
    busca: 'cadeira de alimentação bebê',
  },

  // Roupas
  {
    id: 'body-curto',
    nome: 'Body manga curta',
    categoria: 'roupas',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 6,
    porque: 'Base do dia a dia. Prefira mais peças no tamanho P do que no RN.',
    busca: 'body bebê manga curta',
  },
  {
    id: 'body-longo',
    nome: 'Body manga longa',
    categoria: 'roupas',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 6,
    porque: 'Para dias mais frios ou ambientes com ar-condicionado.',
    busca: 'body bebê manga longa',
  },
  {
    id: 'mijao',
    nome: 'Mijão (calça com pé)',
    categoria: 'roupas',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 6,
    porque: 'Combina com os bodies e mantém os pés aquecidos.',
    busca: 'mijão bebê',
  },
  {
    id: 'macacao',
    nome: 'Macacão',
    categoria: 'roupas',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 4,
    porque: 'Peça única, prática para dormir e para as trocas.',
    busca: 'macacão bebê',
  },
  {
    id: 'meias',
    nome: 'Meias',
    categoria: 'roupas',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 6,
    porque: 'Os pés do recém-nascido perdem calor com facilidade.',
    busca: 'meia bebê',
    precoPor: 'par',
  },
  {
    id: 'casaquinho',
    nome: 'Casaquinho',
    categoria: 'roupas',
    prioridade: 'util',
    quando: 'tri3',
    quantidade: 2,
    porque: 'A quantidade depende do clima da sua cidade e da estação do nascimento.',
    busca: 'casaquinho bebê',
  },
  {
    id: 'touca',
    nome: 'Touca',
    categoria: 'roupas',
    prioridade: 'util',
    quando: 'maternidade',
    quantidade: 2,
    porque: 'Ajuda a manter a temperatura nos primeiros dias, principalmente no frio.',
    busca: 'touca recém-nascido',
  },
  {
    id: 'luvas',
    nome: 'Luvas',
    categoria: 'roupas',
    prioridade: 'opcional',
    quando: 'tri3',
    quantidade: 2,
    porque: 'Evitam arranhões no rosto, mas manter as unhas curtas também resolve.',
    busca: 'luva recém-nascido',
    precoPor: 'par',
  },
  {
    id: 'manta',
    nome: 'Manta',
    categoria: 'roupas',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 2,
    porque: 'Para carregar e passear. No berço, não deixe a manta solta.',
    fonte: SONO_SEGURO,
    busca: 'manta bebê',
  },
  {
    id: 'saida-maternidade',
    nome: 'Roupa de saída da maternidade',
    categoria: 'roupas',
    prioridade: 'util',
    quando: 'maternidade',
    quantidade: 1,
    porque: 'Conjunto confortável e adequado ao clima do dia da alta.',
    busca: 'saída de maternidade',
    precoPor: 'conjunto',
  },
  {
    id: 'sapatinho',
    nome: 'Sapatinho',
    categoria: 'roupas',
    prioridade: 'opcional',
    quando: 'depois',
    quantidade: 1,
    porque: 'O bebê ainda não anda. Meias costumam bastar nos primeiros meses.',
    busca: 'sapatinho bebê',
    precoPor: 'par',
  },

  // Saúde
  {
    id: 'termometro',
    nome: 'Termômetro digital',
    categoria: 'saude',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 1,
    porque:
      'Para medir a temperatura com segurança. Febre em recém-nascido exige avaliação médica.',
    busca: 'termômetro digital',
  },
  {
    id: 'soro-fisiologico',
    nome: 'Soro fisiológico',
    categoria: 'saude',
    prioridade: 'essencial',
    quando: 'tri3',
    quantidade: 2,
    porque: 'Usado na higiene do nariz. Siga a orientação do pediatra.',
    busca: 'soro fisiológico 0,9%',
    precoPor: 'frasco',
  },
  {
    id: 'aspirador-nasal',
    nome: 'Aspirador nasal',
    categoria: 'saude',
    prioridade: 'util',
    quando: 'depois',
    quantidade: 1,
    porque: 'Ajuda quando o bebê está com o nariz entupido.',
    busca: 'aspirador nasal bebê',
  },
  {
    id: 'umidificador',
    nome: 'Umidificador de ar',
    categoria: 'saude',
    prioridade: 'opcional',
    quando: 'depois',
    quantidade: 1,
    porque: 'Útil em cidades com ar muito seco. Precisa de limpeza frequente.',
    busca: 'umidificador de ar',
  },

  // Mala da maternidade (para a mãe)
  {
    id: 'absorvente-pos-parto',
    nome: 'Absorvente pós-parto',
    categoria: 'maternidade',
    prioridade: 'essencial',
    quando: 'maternidade',
    quantidade: 2,
    porque:
      'O sangramento pós-parto é normal nas primeiras semanas. Confira a lista da sua maternidade.',
    busca: 'absorvente pós-parto',
    precoPor: 'pacote',
  },
  {
    id: 'camisola-abertura',
    nome: 'Camisola ou pijama com abertura frontal',
    categoria: 'maternidade',
    prioridade: 'essencial',
    quando: 'maternidade',
    quantidade: 3,
    porque: 'Facilita a amamentação na maternidade e nas primeiras semanas em casa.',
    busca: 'camisola amamentação',
  },
  {
    id: 'calcinha-pos-parto',
    nome: 'Calcinha pós-parto',
    categoria: 'maternidade',
    prioridade: 'essencial',
    quando: 'maternidade',
    quantidade: 4,
    porque: 'Modelos de cintura alta e algodão são mais confortáveis, inclusive após cesárea.',
    busca: 'calcinha pós-parto',
  },
  {
    id: 'cinta-pos-parto',
    nome: 'Cinta pós-parto',
    categoria: 'maternidade',
    prioridade: 'opcional',
    quando: 'maternidade',
    quantidade: 1,
    porque: 'Use apenas se o obstetra indicar.',
    busca: 'cinta pós-parto',
  },

  // Segurança da casa
  {
    id: 'protetor-tomada',
    nome: 'Protetor de tomada',
    categoria: 'seguranca',
    prioridade: 'util',
    quando: 'depois',
    quantidade: 1,
    porque: 'Necessário quando o bebê começar a engatinhar. Costuma vir em kits com várias peças.',
    busca: 'protetor de tomada',
    precoPor: 'kit',
  },
  {
    id: 'trava-gaveta',
    nome: 'Trava de gaveta e armário',
    categoria: 'seguranca',
    prioridade: 'util',
    quando: 'depois',
    quantidade: 1,
    porque:
      'Impede o acesso a produtos de limpeza e objetos perigosos. Costuma vir em kits com várias peças.',
    busca: 'trava de gaveta bebê',
    precoPor: 'kit',
  },
  {
    id: 'portao-seguranca',
    nome: 'Portão de segurança',
    categoria: 'seguranca',
    prioridade: 'opcional',
    quando: 'depois',
    quantidade: 1,
    porque: 'Para casas com escadas. Pode esperar o bebê começar a se locomover.',
    busca: 'portão de segurança escada',
  },
];
